import { LayoutOption, ColorSchemeOption, TypographyOption, ColorScheme, Product, Category } from './types';

export const COLOR_SCHEMES: Record<ColorSchemeOption, ColorScheme> = {
  [ColorSchemeOption.BlackGold]: {
    light: {
        primary: '#E8C547',
        primaryHsl: '47, 81%, 60%',
        secondary: '#14213D',
        background: '#FFFFFF',
        textPrimary: '#1A202C',
        textSecondary: '#4A5568',
        success: '#DAB449'
    },
    dark: {
      primary: '#F0B429',
      primaryHsl: '42, 87%, 54%',
      secondary: '#14213D',
      background: '#1A202C',
      textPrimary: '#E5E5E5',
      textSecondary: '#A9A9A9',
      success: '#F0B429',
    },
    defaultMode: 'dark',
  },
};

export const LAYOUT_OPTIONS = [
  { id: LayoutOption.ModernSleek, label: 'Modern & Sleek' },
];

export const COLOR_SCHEME_OPTIONS = [
  { id: ColorSchemeOption.BlackGold, label: 'Black & Gold' },
];

export const TYPOGRAPHY_OPTIONS = [
  { id: TypographyOption.LuxeModern, label: 'Luxe Modern' },
];

export const PRODUCTS: Product[] = [
  { id: 1, nameKey: 'product_sofa_name', categoryKey: 'sofas', imageUrl: 'https://picsum.photos/seed/sofa/800/600' },
  { id: 2, nameKey: 'product_chair_name', categoryKey: 'armchairs', imageUrl: 'https://picsum.photos/seed/chair/800/600' },
  { id: 3, nameKey: 'product_table_name', categoryKey: 'dining_room', imageUrl: 'https://picsum.photos/seed/table/800/600' },
  { id: 4, nameKey: 'product_lamp_name', categoryKey: 'decor_accessories', imageUrl: 'https://picsum.photos/seed/lamp/800/600' },
  { id: 5, nameKey: 'product_bed_name', categoryKey: 'bedroom', imageUrl: 'https://picsum.photos/seed/bed/800/600' },
  { id: 6, nameKey: 'product_cabinet_name', categoryKey: 'office', imageUrl: 'https://picsum.photos/seed/cabinet/800/600' },
];

export const TEXTS: Record<string, Record<string, string>> = {
  en: {
    nav_home: 'Home',
    nav_shop: 'Shop',
    nav_about: 'About',
    nav_contact: 'Contact',
    lang_toggle_en: 'English',
    lang_toggle_ar: 'العربية',
    hero_sleek_title: 'The Future of Design',
    hero_cta_explore: 'Explore',
    products_title: 'Featured Collections',
    products_subtitle: 'Hand-selected pieces that define elegance and comfort.',
    visit_us_title: 'Visit Us',
    visit_us_p1: 'We are delighted to welcome you. Come and enjoy a warm cup of coffee with our expert designers together, we’ll create the kitchen of your dreams. At our showroom, inspiration meets craftsmanship, and whatever your style may be, you’ll always find something made just for you.',
    footer_locations_title: 'Our Branches',
    footer_cairo_branch_title: 'Cairo Branch',
    footer_cairo_branch_address: '66 Mohamed refaat Street, next to kfc, El Nozha El Gadida',
    footer_minya_branch_title: 'Minya Branch',
    footer_minya_branch_address: '6 Mostafa Kamel Street, Ard Sultan',
    footer_new_minya_branch_title: 'New Minya Branch',
    footer_new_minya_branch_address: 'Corner Plaza Mall, 2nd Floor, Third District',
    footer_phone_title: 'Contact Us',
    footer_phone_label: 'Phone:',
    footer_phone_number: '01010279777',
    footer_hours: 'Hours: 12 PM - 10 PM (Mon-Sat)',
    footer_copyright: '© 2024 Raafat Furniture. All Rights Reserved.',
    product_sofa_name: 'The Nile Sofa',
    product_chair_name: 'Pharaoh Armchair',
    product_table_name: 'Luxor Dining Table',
    product_lamp_name: 'Giza Floor Lamp',
    product_bed_name: 'Cleopatra Bed',
    product_cabinet_name: 'Alexandria Cabinet',
    search_placeholder: 'Search for furniture, styles, and more...',
    cat_living_room: 'Living Room',
    cat_sofa_sets: 'Sofa Sets',
    cat_sectionals: 'Sectionals',
    cat_sofas: 'Sofas',
    cat_armchairs: 'Armchairs',
    cat_recliners: 'Recliners',
    cat_bedroom: 'Bedroom',
    cat_dining_room: 'Dining Room',
    cat_kids_youth: 'Kids & Youth Rooms',
    cat_office: 'Office Furniture',
    cat_outdoor: 'Outdoor Furniture',
    cat_coffee_tables: 'Coffee Tables',
    cat_side_tables: 'Side Tables',
    cat_tv_units: 'TV Units',
    cat_consoles: 'Consoles',
    cat_decor_accessories: 'Decor & Accessories',
    cat_curtains: 'Curtains',
    cat_mattresses: 'Mattresses',
    cat_pillows: 'Pillows',
    // Login & Account
    login_create_account: 'Create an Account',
    login_welcome_back: 'Welcome Back',
    login_signup_desc: 'Sign up to save your preferences and receive updates.',
    login_signin_desc: 'Sign in to access your account.',
    login_email: 'Email address',
    login_password: 'Password',
    login_creating: 'Creating Account...',
    login_signing_in: 'Signing In...',
    login_btn_create: 'Create Account',
    login_btn_signin: 'Sign In',
    login_or_continue: 'Or continue with',
    login_google: 'Google',
    login_already_have: 'Already have an account? Sign in',
    login_dont_have: "Don't have an account? Sign up",
    account_title: 'My Account',
    account_email: 'Email',
    account_signout: 'Sign Out',
    // Admin
    admin_dashboard: 'Admin Dashboard',
    admin_tab_categories: 'Categories',
    admin_tab_archive: 'Archive',
    admin_tab_logs: 'Activity Logs',
    admin_listings: 'Listings',
    admin_add_new: 'Add New Listing',
    admin_create_new: 'Create New Listing',
    admin_name_en: 'Product Name (English)',
    admin_name_ar: 'Product Name (Arabic)',
    admin_category: 'Category',
    admin_desc_en: 'Description (English)',
    admin_desc_ar: 'Description (Arabic)',
    admin_auto_translate: 'Auto-Translate to Arabic',
    admin_image: 'Product Image',
    admin_upload_image: 'Upload Image',
    admin_cancel: 'Cancel',
    admin_btn_create: 'Create Listing',
    admin_btn_creating: 'Creating...',
    admin_archived: 'Archived Listings',
    admin_restore: 'Restore',
    admin_delete_perm: 'Delete Permanently',
    admin_recent_activity: 'Recent Activity',
    admin_no_logs: 'No logs available.',
    admin_no_listings: 'No listings found in this category.',
    admin_no_archived: 'No archived listings found.',
    admin_delete: 'Delete',
    admin_archive: 'Archive',
    admin_edit: 'Edit',
    admin_save: 'Save',
    admin_panel: 'Admin Panel',
    admin_back_to_site: 'Back to Site',
    admin_select_category: 'Select a category to view or add listings.',
    admin_items: 'Items',
    admin_pending_deletion: 'Pending Deletion',
    admin_days_left: 'days left before deletion',
    admin_recover: 'Recover',
    admin_time: 'Time',
    admin_admin: 'Admin',
    admin_action: 'Action',
    admin_details: 'Details',
    admin_photo_min: 'Photo (Minimum 1)',
    admin_click_to_change: 'Click to change',
    admin_click_to_upload: 'Click to upload photo',
    admin_photo_format: 'PNG, JPG up to 5MB',
    admin_post_listing: 'Post Listing',
    admin_remove_listing: 'Remove this listing?',
    admin_archived_auto_remove: 'Archived listings will automatically be removed in 14 days.',
    admin_access_denied: 'Access Denied',
    admin_not_authorized: 'Your email ({email}) is not authorized to view this page. Please contact the administrator.',
    admin_placeholder_name_en: 'e.g. Modern Sofa',
    admin_placeholder_name_ar: 'أريكة حديثة',
    admin_placeholder_desc_en: 'Product details...',
    admin_placeholder_desc_ar: 'تفاصيل المنتج...',
    admin_alert_name_required: 'Please provide a product name in at least one language.',
    admin_alert_desc_required: 'Please provide a description in at least one language.',
    admin_alert_translate_failed: 'Failed to auto-translate. Please fill in all fields manually or try again.',
    admin_alert_delete_failed: 'Failed to delete product.',
    admin_alert_create_failed: 'Failed to create listing: ',
    nav_go_back: 'Go Back',
    shop_not_found: 'Category not found.',
    shop_return_home: 'Return Home',
    shop_artisans_work: 'Artisans at Work',
    shop_curating_desc: 'We are currently curating excellence for this collection. Check back soon for masterpieces in progress.',
    search_results_for: 'Search Results for',
    search_no_results: 'No results found for',
    product_not_found: 'Product Not Found',
    product_return_home: 'Return to Home',
    product_inquire_now: 'Inquire Now',
    product_fallback_desc: 'This is a detailed view for {name}. In a fully implemented CMS, this description would be fetched from the database, allowing admins to update the text, specifications, and additional images securely.',
    aria_close_search: 'Close search',
    aria_switch_light: 'Switch to light mode',
    aria_switch_dark: 'Switch to dark mode',
    aria_account: 'Account',
    aria_open_menu: 'Open menu',
    aria_close_menu: 'Close menu',
    aria_logo: 'Raafat Furniture Logo',
    cart: 'Your Cart',
    cart_empty: 'Your cart is empty.',
    continue_shopping: 'Continue Shopping',
    save_for_later: 'Save for later',
    saved_for_later: 'Saved for later',
    move_to_cart: 'Move to cart',
    remove: 'Remove',
    subtotal: 'Subtotal',
    shipping_taxes_calculated: 'Shipping and taxes calculated at checkout.',
    checkout: 'Checkout',
    sign_in_to_save: 'Sign in to save items',
    create_account_wishlist: 'Create an account or sign in to save items to your wishlist.',
    sign_in: 'Sign In',
    create_account: 'Create Account',
    cancel: 'Cancel',
    price_on_request: 'Price on Request',
    clear_filters: 'Clear Filters',
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_shop: 'المجموعات',
    nav_about: 'نبذة عنا',
    nav_contact: 'اتصل بنا',
    lang_toggle_en: 'English',
    lang_toggle_ar: 'العربية',
    hero_sleek_title: 'مستقبل التصميم',
    hero_cta_explore: 'استكشف',
    products_title: 'مجموعاتنا المميزة',
    products_subtitle: 'قطعٌ فنية مختارة بعناية لتعيد تعريف الأناقة والراحة في مساحاتكم.',
    visit_us_title: 'زورونا',
    visit_us_p1: 'يسعدنا أن نرحب بكم. تعالوا واستمتعوا بفنجان من القهوة الدافئة مع مصممينا الخبراء، وسنصنع معًا مطبخ أحلامكم. في صالة العرض لدينا، يلتقي الإلهام بالحرفية، ومهما كان أسلوبكم، ستجدون دائمًا شيئًا مصنوعًا خصيصًا لكم.',
    footer_locations_title: 'الفروع',
    footer_cairo_branch_title: 'فرع القاهرة',
    footer_cairo_branch_address: '٦٦ شارع المؤرخ محمد رفعت بجوار كنتاكي خلف السندباد، النزهة الجديدة',
    footer_minya_branch_title: 'فرع المنيا',
    footer_minya_branch_address: '٦ شارع مصطفي كامل، أرض سلطان',
    footer_new_minya_branch_title: 'فرع المنيا الجديدة',
    footer_new_minya_branch_address: 'مول كورنر بلازا، الدور الثاني، الحي الثالث',
    footer_phone_title: 'اتصل بنا',
    footer_phone_label: 'الهاتف:',
    footer_phone_number: '01010279777',
    footer_hours: 'ساعات العمل: ١٢ ظهراً - ١٠ مساءً (من الإثنين إلى السبت)',
    footer_copyright: '© 2024 رأفت للأثاث. جميع الحقوق محفوظة.',
    product_sofa_name: 'أريكة النيل',
    product_chair_name: 'مقعد فرعون',
    product_table_name: 'طاولة طعام الأقصر',
    product_lamp_name: 'مصباح الجيزة الأرضي',
    product_bed_name: 'سرير كليوباترا',
    product_cabinet_name: 'خزانة الإسكندرية',
    search_placeholder: 'ابحث عن الأثاث والأنماط والمزيد...',
    cat_living_room: 'غرفة المعيشة',
    cat_sofa_sets: 'أطقم أرائك',
    cat_sectionals: 'أرائك ركنية',
    cat_sofas: 'أرائك',
    cat_armchairs: 'كراسي بمساند',
    cat_recliners: 'كراسي استرخاء',
    cat_bedroom: 'غرفة النوم',
    cat_dining_room: 'غرفة الطعام',
    cat_kids_youth: 'غرف الأطفال والشباب',
    cat_office: 'أثاث مكتبي',
    cat_outdoor: 'أثاث خارجي',
    cat_coffee_tables: 'طاولات قهوة',
    cat_side_tables: 'طاولات جانبية',
    cat_tv_units: 'وحدات تلفزيون',
    cat_consoles: 'كونسول',
    cat_decor_accessories: 'ديكور وإكسسوارات',
    cat_curtains: 'ستائر',
    cat_mattresses: 'مراتب',
    cat_pillows: 'وسائد',
    // Login & Account
    login_create_account: 'إنشاء حساب',
    login_welcome_back: 'مرحباً بعودتك',
    login_signup_desc: 'سجل لإنشاء حساب وحفظ تفضيلاتك وتلقي التحديثات.',
    login_signin_desc: 'سجل الدخول للوصول إلى حسابك.',
    login_email: 'البريد الإلكتروني',
    login_password: 'كلمة المرور',
    login_creating: 'جاري إنشاء الحساب...',
    login_signing_in: 'جاري تسجيل الدخول...',
    login_btn_create: 'إنشاء حساب',
    login_btn_signin: 'تسجيل الدخول',
    login_or_continue: 'أو تابع باستخدام',
    login_google: 'جوجل',
    login_already_have: 'لديك حساب بالفعل؟ سجل الدخول',
    login_dont_have: 'ليس لديك حساب؟ قم بإنشاء حساب',
    account_title: 'حسابي',
    account_email: 'البريد الإلكتروني',
    account_signout: 'تسجيل الخروج',
    // Admin
    admin_dashboard: 'لوحة تحكم الإدارة',
    admin_tab_categories: 'الفئات',
    admin_tab_archive: 'الأرشيف',
    admin_tab_logs: 'سجلات النشاط',
    admin_listings: 'المنتجات',
    admin_add_new: 'إضافة منتج جديد',
    admin_create_new: 'إنشاء منتج جديد',
    admin_name_en: 'اسم المنتج (إنجليزي)',
    admin_name_ar: 'اسم المنتج (عربي)',
    admin_category: 'الفئة',
    admin_desc_en: 'الوصف (إنجليزي)',
    admin_desc_ar: 'الوصف (عربي)',
    admin_auto_translate: 'ترجمة تلقائية للعربية',
    admin_image: 'صورة المنتج',
    admin_upload_image: 'رفع صورة',
    admin_cancel: 'إلغاء',
    admin_btn_create: 'إنشاء المنتج',
    admin_btn_creating: 'جاري الإنشاء...',
    admin_archived: 'المنتجات المؤرشفة',
    admin_restore: 'استعادة',
    admin_delete_perm: 'حذف نهائي',
    admin_recent_activity: 'النشاط الأخير',
    admin_no_logs: 'لا توجد سجلات متاحة.',
    admin_no_listings: 'لم يتم العثور على منتجات في هذه الفئة.',
    admin_no_archived: 'لم يتم العثور على منتجات مؤرشفة.',
    admin_delete: 'حذف',
    admin_archive: 'أرشفة',
    admin_edit: 'تعديل',
    admin_save: 'حفظ',
    admin_panel: 'لوحة تحكم الإدارة',
    admin_back_to_site: 'العودة للموقع',
    admin_select_category: 'حدد فئة لعرض أو إضافة منتجات.',
    admin_items: 'عناصر',
    admin_pending_deletion: 'في انتظار الحذف',
    admin_days_left: 'أيام متبقية قبل الحذف',
    admin_recover: 'استعادة',
    admin_time: 'الوقت',
    admin_admin: 'المسؤول',
    admin_action: 'الإجراء',
    admin_details: 'التفاصيل',
    admin_photo_min: 'الصورة (واحدة على الأقل)',
    admin_click_to_change: 'انقر للتغيير',
    admin_click_to_upload: 'انقر لرفع صورة',
    admin_photo_format: 'PNG, JPG حتى 5 ميجابايت',
    admin_post_listing: 'نشر المنتج',
    admin_remove_listing: 'هل تريد إزالة هذا المنتج؟',
    admin_archived_auto_remove: 'ستتم إزالة المنتجات المؤرشفة تلقائيًا بعد 14 يومًا.',
    admin_access_denied: 'تم رفض الوصول',
    admin_not_authorized: 'بريدك الإلكتروني ({email}) غير مصرح له بعرض هذه الصفحة. يرجى الاتصال بالمسؤول.',
    admin_placeholder_name_en: 'مثال: أريكة حديثة',
    admin_placeholder_name_ar: 'أريكة حديثة',
    admin_placeholder_desc_en: 'تفاصيل المنتج...',
    admin_placeholder_desc_ar: 'تفاصيل المنتج...',
    admin_alert_name_required: 'يرجى تقديم اسم المنتج بلغة واحدة على الأقل.',
    admin_alert_desc_required: 'يرجى تقديم وصف للمنتج بلغة واحدة على الأقل.',
    admin_alert_translate_failed: 'فشلت الترجمة التلقائية. يرجى ملء جميع الحقول يدوياً أو المحاولة مرة أخرى.',
    admin_alert_delete_failed: 'فشل حذف المنتج.',
    admin_alert_create_failed: 'فشل إنشاء المنتج: ',
    nav_go_back: 'العودة',
    shop_not_found: 'الفئة غير موجودة.',
    shop_return_home: 'العودة للرئيسية',
    shop_artisans_work: 'الحرفيون يعملون',
    shop_curating_desc: 'نحن نعمل حالياً على تنسيق التميز لهذه المجموعة. ترقبوا روائعنا قيد التنفيذ قريباً.',
    search_results_for: 'نتائج البحث عن',
    search_no_results: 'لم يتم العثور على نتائج لـ',
    product_not_found: 'المنتج غير موجود',
    product_return_home: 'العودة للرئيسية',
    product_inquire_now: 'استفسر الآن',
    product_fallback_desc: 'هذا عرض تفصيلي لـ {name}. في نظام إدارة المحتوى المكتمل، سيتم جلب هذا الوصف من قاعدة البيانات، مما يسمح للمسؤولين بتحديث النص والمواصفات والصور الإضافية بشكل آمن.',
    aria_close_search: 'إغلاق البحث',
    aria_switch_light: 'التبديل للوضع الفاتح',
    aria_switch_dark: 'التبديل للوضع الداكن',
    aria_account: 'الحساب',
    aria_open_menu: 'فتح القائمة',
    aria_close_menu: 'إغلاق القائمة',
    aria_logo: 'شعار رأفت للأثاث',
    cart: 'عربة التسوق',
    cart_empty: 'عربة التسوق فارغة.',
    continue_shopping: 'مواصلة التسوق',
    save_for_later: 'حفظ لوقت لاحق',
    saved_for_later: 'تم الحفظ لوقت لاحق',
    move_to_cart: 'نقل إلى العربة',
    remove: 'إزالة',
    subtotal: 'المجموع الفرعي',
    shipping_taxes_calculated: 'يتم حساب الشحن والضرائب عند الدفع.',
    checkout: 'الدفع',
    sign_in_to_save: 'سجل الدخول لحفظ العناصر',
    create_account_wishlist: 'قم بإنشاء حساب أو تسجيل الدخول لحفظ العناصر في قائمة الرغبات الخاصة بك.',
    sign_in: 'تسجيل الدخول',
    create_account: 'إنشاء حساب',
    cancel: 'إلغاء',
    price_on_request: 'السعر عند الطلب',
    clear_filters: 'مسح الفلاتر',
  }
};

export const CATEGORIES: Category[] = [
  { 
    id: 'living_room', 
    labelKey: 'cat_living_room', 
    imageUrl: 'https://picsum.photos/seed/livingroom/800/600',
    subCategories: [
      { id: 'sofa_sets', labelKey: 'cat_sofa_sets', imageUrl: 'https://picsum.photos/seed/sofaset/800/600' },
      { id: 'sectionals', labelKey: 'cat_sectionals', imageUrl: 'https://picsum.photos/seed/sectional/800/600' },
      { id: 'sofas', labelKey: 'cat_sofas', imageUrl: 'https://picsum.photos/seed/sofa/800/600' },
      { id: 'armchairs', labelKey: 'cat_armchairs', imageUrl: 'https://picsum.photos/seed/armchair/800/600' },
      { id: 'recliners', labelKey: 'cat_recliners', imageUrl: 'https://picsum.photos/seed/recliner/800/600' },
    ]
  },
  { id: 'bedroom', labelKey: 'cat_bedroom', imageUrl: 'https://picsum.photos/seed/bedroom/800/600' },
  { id: 'dining_room', labelKey: 'cat_dining_room', imageUrl: 'https://picsum.photos/seed/dining/800/600' },
  { id: 'kids_youth', labelKey: 'cat_kids_youth', imageUrl: 'https://picsum.photos/seed/kidsroom/800/600' },
  { id: 'office', labelKey: 'cat_office', imageUrl: 'https://picsum.photos/seed/office/800/600' },
  { id: 'outdoor', labelKey: 'cat_outdoor', imageUrl: 'https://picsum.photos/seed/outdoor/800/600' },
  { id: 'coffee_tables', labelKey: 'cat_coffee_tables', imageUrl: 'https://picsum.photos/seed/coffeetable/800/600' },
  { id: 'side_tables', labelKey: 'cat_side_tables', imageUrl: 'https://picsum.photos/seed/sidetable/800/600' },
  { id: 'tv_units', labelKey: 'cat_tv_units', imageUrl: 'https://picsum.photos/seed/tvunit/800/600' },
  { id: 'consoles', labelKey: 'cat_consoles', imageUrl: 'https://picsum.photos/seed/console/800/600' },
  { id: 'decor_accessories', labelKey: 'cat_decor_accessories', imageUrl: 'https://picsum.photos/seed/decor/800/600' },
  { id: 'curtains', labelKey: 'cat_curtains', imageUrl: 'https://picsum.photos/seed/curtains/800/600' },
  { id: 'mattresses', labelKey: 'cat_mattresses', imageUrl: 'https://picsum.photos/seed/mattress/800/600' },
  { id: 'pillows', labelKey: 'cat_pillows', imageUrl: 'https://picsum.photos/seed/pillows/800/600' }
];