import { LayoutOption, ColorSchemeOption, TypographyOption, ColorScheme, Product, Category } from './types';

export const COLOR_SCHEMES: Record<ColorSchemeOption, ColorScheme> = {
  [ColorSchemeOption.BlackGold]: {
    light: {
        primary: '#C9A227',
        primaryHsl: '44, 70%, 47%',
        secondary: '#14213D',
        background: '#F3F0E8',
        textPrimary: '#14213D',
        textSecondary: '#5A6578',
        success: '#C9A227'
    },
    dark: {
      primary: '#E8C547',
      primaryHsl: '47, 81%, 60%',
      secondary: '#14213D',
      background: '#1A202C',
      textPrimary: '#E5E5E5',
      textSecondary: '#A9A9A9',
      success: '#DAB449',
    },
    defaultMode: 'light',
  },
};

export const LAYOUT_OPTIONS = [
  { id: LayoutOption.ModernSleek, label: 'Modern & Sleek' },
];

export const COLOR_SCHEME_OPTIONS = [
  { id: ColorSchemeOption.BlackGold, label: 'Black & Gold' },
];

export const TYPOGRAPHY_OPTIONS = [
  { id: TypographyOption.LuxeModern, label: 'Luxe Modern' },
];

export const PRODUCTS: Product[] = [
  { id: 1, nameKey: 'product_sofa_name', categoryKey: 'sofas', imageUrl: 'https://picsum.photos/seed/sofa/800/600' },
  { id: 2, nameKey: 'product_chair_name', categoryKey: 'armchairs', imageUrl: 'https://picsum.photos/seed/chair/800/600' },
  { id: 3, nameKey: 'product_table_name', categoryKey: 'dining_room', imageUrl: 'https://picsum.photos/seed/table/800/600' },
  { id: 4, nameKey: 'product_lamp_name', categoryKey: 'decor_accessories', imageUrl: 'https://picsum.photos/seed/lamp/800/600' },
  { id: 5, nameKey: 'product_bed_name', categoryKey: 'bedroom', imageUrl: 'https://picsum.photos/seed/bed/800/600' },
  { id: 6, nameKey: 'product_cabinet_name', categoryKey: 'office', imageUrl: 'https://picsum.photos/seed/cabinet/800/600' },
];

export const TEXTS: Record<string, Record<string, string>> = {
  en: {
    nav_home: 'Home',
    nav_shop: 'Shop',
    nav_about: 'About',
    nav_contact: 'Contact',
    lang_toggle_en: 'English',
    lang_toggle_ar: 'العربية',
    hero_sleek_title: 'The Future of Design',
    hero_cta_explore: 'Explore',
    products_title: 'Featured Collections',
    products_subtitle: 'Hand-selected pieces that define elegance and comfort.',
    visit_us_title: 'Visit Us',
    visit_us_p1: 'Visit our showrooms in Cairo, Minya, and New Minya. Touch the fabrics, see the finishes, and talk with our team about custom pieces, over coffee if you like.',
    footer_locations_title: 'Our Branches',
    footer_cairo_branch_title: 'Cairo Branch',
    footer_cairo_branch_address: '66 Mohamed refaat Street, next to kfc, El Nozha El Gadida',
    footer_minya_branch_title: 'Minya Branch',
    footer_minya_branch_address: '6 Mostafa Kamel Street, Ard Sultan',
    footer_new_minya_branch_title: 'New Minya Branch',
    footer_new_minya_branch_address: 'Corner Plaza Mall, 2nd Floor, Third District',
    footer_phone_title: 'Contact Us',
    footer_phone_label: 'Phone:',
    footer_phone_number: '01010279777',
    footer_hours: 'Hours: 12 PM to 10 PM, Mon-Sat (Egypt time)',
    footer_tagline: 'Handcrafted luxury furniture',
    footer_copyright: '© 2024 Raafat Furniture. All Rights Reserved.',
    product_sofa_name: 'The Nile Sofa',
    product_chair_name: 'Pharaoh Armchair',
    product_table_name: 'Luxor Dining Table',
    product_lamp_name: 'Giza Floor Lamp',
    product_bed_name: 'Cleopatra Bed',
    product_cabinet_name: 'Alexandria Cabinet',
    search_placeholder: 'Search for furniture, styles, and more...',
    cat_living_room: 'Living Room',
    cat_sofa_sets: 'Sofa Sets',
    cat_sectionals: 'Sectionals',
    cat_sofas: 'Sofas',
    cat_armchairs: 'Armchairs',
    cat_recliners: 'Recliners',
    cat_bedroom: 'Bedroom',
    cat_dining_room: 'Dining Room',
    cat_kids_youth: 'Kids & Youth Rooms',
    cat_office: 'Office Furniture',
    cat_outdoor: 'Outdoor Furniture',
    cat_coffee_tables: 'Coffee Tables',
    cat_side_tables: 'Side Tables',
    cat_decor_accessories: 'Decor & Accessories',
    cat_curtains: 'Curtains',
    cat_mattresses: 'Mattresses',
    cat_pillows: 'Pillows',
    // Login & Account
    login_create_account: 'Create an Account',
    login_welcome_back: 'Welcome Back',
    login_signup_desc: 'Sign up to save your preferences and receive updates.',
    login_signin_desc: 'Sign in to access your account.',
    login_email: 'Email address',
    login_password: 'Password',
    login_creating: 'Creating Account...',
    login_signing_in: 'Signing In...',
    login_btn_create: 'Create Account',
    login_btn_signin: 'Sign In',
    login_or_continue: 'Or continue with',
    login_google: 'Continue with Google',
    login_google_only_desc: 'Sign in with Google to continue. This keeps your account secure and reduces spam.',
    login_google_error: 'Google sign-in failed. Please try again.',
    login_terms_note: 'By continuing you agree to our Terms of Service and Privacy Policy.',
    use_my_location: 'Use my location',
    near_hint_placeholder: 'City or postal code (e.g. Cairo, 11771)',
    sort_nearest: 'Nearest',
    sort_by_my_location: 'Sort by my location',
    sort_showrooms: 'Sort showrooms',
    or_type_city: 'Or type a city / postal code',
    pickup_sort_help: 'Sort showrooms by how close they are to you — then tap a showroom to select it.',
    geo_unsupported: 'Location is not available in this browser.',
    geo_denied: 'Could not read your location. Try a city or postal code instead.',
    geo_hint_unknown: 'Could not match that city or postal code. Try Cairo, Minya, Alexandria, or a 5-digit postal code.',
    billing_for_card: 'Card payments need a billing address (where your card is registered).',
    pickup_collect_here: 'You will collect your order from this showroom.',
    pickup_no_address_needed: 'No delivery address needed for transfer payments — collect from the showroom above.',
    billing_address: 'Billing address',
    pickup_confirm: 'Confirm pickup',
    login_already_have: 'Already have an account? Sign in',
    login_dont_have: "Don't have an account? Sign up",
    account_title: 'My Account',
    account_email: 'Email',
    account_signout: 'Log out',
    // Admin
    admin_dashboard: 'Admin Dashboard',
    admin_tab_categories: 'Categories',
    admin_tab_archive: 'Archive',
    admin_tab_logs: 'Activity Logs',
    admin_listings: 'Listings',
    admin_add_new: 'Add New Listing',
    admin_create_new: 'Create New Listing',
    admin_name_en: 'Product Name (English)',
    admin_name_ar: 'Product Name (Arabic)',
    admin_category: 'Category',
    admin_price: 'Price',
    admin_optional: 'Optional',
    admin_placeholder_price: 'Leave blank for "Price on Request"',
    admin_desc_en: 'Description (English)',
    admin_desc_ar: 'Description (Arabic)',
    admin_auto_translate: 'Auto-Translate to Arabic',
    admin_image: 'Product Image',
    admin_upload_image: 'Upload Image',
    admin_cancel: 'Cancel',
    admin_btn_create: 'Create Listing',
    admin_btn_creating: 'Creating...',
    admin_archived: 'Archived Listings',
    admin_restore: 'Restore',
    admin_delete_perm: 'Delete Permanently',
    admin_delete_perm_warn: 'This permanently deletes the listing and its images. This cannot be undone.',
    admin_recent_activity: 'Recent Activity',
    admin_no_logs: 'No logs available.',
    admin_no_listings: 'No listings found in this category.',
    admin_no_archived: 'No archived listings found.',
    admin_delete: 'Delete',
    admin_archive: 'Archive',
    admin_edit: 'Edit',
    admin_save: 'Save',
    admin_edit_listing: 'Edit Listing',
    admin_update_listing: 'Update Listing',
    admin_panel: 'Admin Panel',
    admin_back_to_site: 'Back to Site',
    admin_select_category: 'Select a category to view or add listings.',
    admin_items: 'Items',
    admin_pending_deletion: 'Pending Deletion',
    admin_days_left: 'days left before deletion',
    admin_recover: 'Recover',
    admin_time: 'Time',
    admin_admin: 'Admin',
    admin_action: 'Action',
    admin_details: 'Details',
    admin_photo_min: 'Photo (Minimum 1)',
    admin_click_to_change: 'Click to change',
    admin_click_to_upload: 'Click to upload photo',
    admin_photo_format: 'PNG, JPG up to 5MB',
    admin_change_photo: 'Change Photo',
    admin_alert_image_required: 'Product image is required',
    account_admin: 'Admin',
    admin_post_listing: 'Post Listing',
    admin_remove_listing: 'Remove this listing?',
    admin_archived_auto_remove: 'Archived listings will automatically be removed in 14 days.',
    admin_access_denied: 'Access Denied',
    coming_soon_title: 'Coming Soon',
    coming_soon_body: 'We are putting the finishing touches on something special. Leave your details and we will let you know the moment we open.',
    coming_soon_scheduled: 'Planned opening',
    coming_soon_notify: 'Notify me',
    coming_soon_name: 'Your name',
    coming_soon_email: 'Email address',
    coming_soon_phone: 'Phone (optional)',
    coming_soon_success: 'You are on the list. We will email you when we launch.',
    coming_soon_privacy: 'We will only use your details to tell you about our launch. See our Privacy Policy.',
    coming_soon_sign_in: 'Team member? Sign in',
    admin_not_authorized: 'Your email ({email}) is not authorized to view this page. Please contact the administrator.',
    admin_placeholder_name_en: 'e.g. Modern Sofa',
    admin_placeholder_name_ar: 'أريكة حديثة',
    admin_placeholder_desc_en: 'Product details...',
    admin_placeholder_desc_ar: 'تفاصيل المنتج...',
    admin_alert_name_required: 'Please provide a product name in at least one language.',
    admin_alert_desc_required: 'Please provide a description in at least one language.',
    admin_alert_translate_failed: 'Failed to auto-translate. Please fill in all fields manually or try again.',
    admin_alert_delete_failed: 'Failed to delete product.',
    admin_alert_create_failed: 'Failed to create listing: ',
    nav_go_back: 'Go Back',
    shop_not_found: 'Category not found.',
    shop_return_home: 'Return Home',
    shop_artisans_work: 'Artisans at Work',
    shop_curating_desc: 'We are currently curating excellence for this collection. Check back soon for masterpieces in progress.',
    search_results_for: 'Search Results for',
    search_no_results: 'No results found for',
    product_not_found: 'Product Not Found',
    product_return_home: 'Return to Home',
    product_inquire_now: 'Inquire Now',
    add_to_cart: 'Add to Cart',
    product_fallback_desc: 'This is a detailed view for {name}. In a fully implemented CMS, this description would be fetched from the database, allowing admins to update the text, specifications, and additional images securely.',
    aria_close_search: 'Close search',
    aria_switch_light: 'Switch to light mode',
    aria_switch_dark: 'Switch to dark mode',
    aria_account: 'Account',
    aria_open_menu: 'Open menu',
    aria_close_menu: 'Close menu',
    mobile_nav: 'Main navigation',
    aria_logo: 'Raafat Furniture Logo',
    cart: 'Your Cart',
    cart_empty: 'Your cart is empty.',
    continue_shopping: 'Continue Shopping',
    save_for_later: 'Save for later',
    saved_for_later: 'Saved for later',
    move_to_cart: 'Move to cart',
    remove: 'Remove',
    subtotal: 'Subtotal',
    shipping_taxes_calculated: 'Shipping and taxes calculated at checkout.',
    checkout: 'Checkout',
    sign_in_to_save: 'Sign in to save items',
    create_account_wishlist: 'Create an account or sign in to save items to your wishlist.',
    sign_in: 'Sign In',
    create_account: 'Create Account',
    cancel: 'Cancel',
    price_on_request: 'Price on Request',
    clear_filters: 'Clear Filters',
    skip_to_content: 'Skip to content',
    color: 'Color',
    material: 'Material',
    dimensions: 'Dimensions',
    custom_dimensions: 'Custom dimensions (optional)',
    custom_dimensions_hint: 'Tell us the size you need — we make to order.',
    custom_dimensions_ph: 'e.g. 220cm W × 95cm D',
    add_to_cart_label: 'Add to Cart',
    added: 'Added',
    added_to_cart: 'Added to cart',
    in_cart_view: 'In cart — view',
    in_cart: 'in cart',
    ar_back: 'Back',
    instapay_send: 'Send',
    instapay_to: 'from any Egyptian bank app to',
    instapay_ref_hint: 'After sending, paste the reference number from your app so we can confirm your payment.',
    ar_exit_hint: 'Swipe back to return to the product',
    decrease_quantity: 'Decrease quantity',
    increase_quantity: 'Increase quantity',
    save: 'Save',
    saved: 'Saved',
    view_3d: '3D & AR',
    view_photos: 'Photos',
    viewer_view_in_ar: 'View in your space',
    viewer_reset: 'Reset view',
    viewer_3d_badge: '3D',
    viewer_ar_qr_title: 'View in AR on your phone',
    viewer_ar_qr_desc: 'Scan this code with your phone to open the model in augmented reality.',
    viewer_ar_qr_hint: 'Scan to open AR',
    prev_image: 'Previous image',
    next_image: 'Next image',
    toggle_wishlist: 'Toggle wishlist',
    checkout_title: 'Checkout',
    order_summary: 'Order summary',
    place_order: 'Place order',
    pay_now: 'Pay now',
    secure_checkout: 'Secure checkout',
    checkout_terms_note: 'By placing your order you agree to our',
    checkout_terms_and: 'and',
    your_details: 'Your details',
    how_to_receive: 'How would you like to receive it?',
    delivery_address: 'Delivery address',
    payment: 'Payment',
    full_name: 'Full name',
    phone: 'Phone',
    phone_optional_hint: 'Optional — helps us reach you about your order',
    no_payment_methods: 'No payment methods are available right now. Please contact the store or try again later.',
    address: 'Address',
    city: 'City',
    governorate: 'Governorate',
    country: 'Country',
    postal_code: 'Postal code',
    order_note: 'Note to the store (optional)',
    free: 'Free',
    shipping_tbd: 'Confirmed after order',
    fulfil_pickup: 'Store pickup',
    fulfil_shipping: 'Delivery',
    fulfil_custom: 'Custom order',
    fulfil_pickup_desc: 'Collect from a Raafat showroom',
    custom_order_title: 'Need something custom?',
    custom_order_checkout_note: 'Bespoke pieces are quoted by our team — contact us with your requirements before ordering.',
    contact_us: 'Contact us',
    fulfil_ship_desc: 'Delivered to your address',
    fulfil_custom_desc: 'Made to your specification',
    pay_card: 'Card / Apple Pay / Google Pay',
    pay_pickup: 'Cash on pickup',
    pay_pickup_desc: 'Pay at the showroom (Egypt only)',
    pay_cod: 'Cash on delivery',
    pay_bank: 'Bank transfer',
    pay_instapay: 'InstaPay',
    pay_instapay_desc: 'Transfer from any Egyptian bank app',
    card_soon: 'Card payments will be available soon. Choose InstaPay, cash or bank transfer for now.',
    shipping_prepaid_note: 'Delivery orders are paid in full when placing the order. Shipping cost is confirmed by the store before dispatch.',
    custom_deposit_note: 'Custom orders require a deposit and are non-returnable once production starts. Our team will contact you to confirm details.',
    transfer_note: 'You’ll receive transfer details on the next page. Your order is confirmed once we verify the payment.',
    vat_included: 'VAT 14% (included)',
    tax_export: 'Tax',
    tax_export_value: '0% (export)',
    duties_note: 'Import duties and taxes, if any, are collected by your country on delivery.',
    tax: 'Tax',
    receipt: 'Receipt',
    verifying_payment: 'Verifying payment',
    view_order: 'View your order',
    confirm_email_prompt: 'Enter the email used on this order to view the receipt.',
    pay_with_instapay: 'Pay with InstaPay',
    pay_by_transfer: 'Pay by bank transfer',
    instapay_step1: 'Send the total below from any Egyptian banking app to our InstaPay address:',
    bank_step1: 'Transfer the total below to our bank account:',
    instapay_note_label: 'In the transfer note / title, write exactly:',
    instapay_note_hint: 'Order number + your name. This is how we match your payment.',
    transfer_step2: 'Copy the transaction reference number from your app.',
    transfer_step3: 'Paste it below so we can verify your payment.',
    transfer_details_soon: 'Our team will send you the transfer details by email shortly.',
    payment_reference: 'Transaction reference',
    submit_reference: 'Submit',
    reference_submitted: 'Reference submitted — we’ll verify your payment shortly.',
    reference_received: 'We received your payment reference and are verifying it. You’ll get a confirmation email once approved.',
    copied: 'Copied',
    tracking_number: 'Tracking number',
    track_order: 'Track order',
    track_title: 'Track your order',
    track_desc: 'Enter your order number and the email you used at checkout.',
    track_cta: 'Track',
    step_awaiting_payment: 'Awaiting payment',
    step_confirmed: 'Order confirmed',
    step_preparing: 'Being prepared',
    step_ready: 'Ready',
    step_shipped: 'Shipped / awaiting pickup',
    step_completed: 'Completed',
    cancelled: 'Cancelled',
    order_cancelled_desc: 'This order was cancelled. Contact us if that’s unexpected.',
    contact_title: 'Contact us',
    contact_desc: 'Questions about a piece, a custom order, or your delivery? We answer within one business day.',
    contact_whatsapp: 'WhatsApp',
    contact_phone: 'Phone',
    contact_form_title: 'Send us a message',
    contact_message: 'Message',
    contact_send: 'Send message',
    contact_sent: 'Message sent',
    contact_sent_desc: 'Thanks — we’ll get back to you shortly.',
    faq_short: 'FAQ',
    faq_title: 'Frequently asked questions',
    faq_desc: 'Everything about ordering, delivery, returns and care.',
    faq_more: 'Still have a question?',
    faq_q1: 'How long does delivery take?',
    faq_a1: 'Delivery time is quoted for each order individually — in-stock, custom, Egypt, and international. Our team confirms the timeline before dispatch.',
    faq_q2: 'Do you deliver outside Egypt?',
    faq_a2: 'Yes — we ship worldwide. Delivery orders are paid in full when placed; the shipping cost is confirmed by our team before dispatch. Import duties, if any, are collected by your country on delivery.',
    faq_q3: 'What payment methods do you accept?',
    faq_a3: 'Card (including Apple Pay and Google Pay), InstaPay, bank transfer, and cash on pickup at our Egyptian showrooms. Delivery orders must be paid before shipping.',
    faq_q4: 'Can I return an item?',
    faq_a4: 'Ready-made items can be returned within 14 days of delivery in unused condition. Custom and made-to-order pieces are non-returnable once production starts. See the full policy in our Terms.',
    faq_q5: 'How do custom orders work?',
    faq_a5: 'Contact us via the Contact page or WhatsApp with your specification. We confirm design, dimensions, materials and price, take a deposit, then start production. Custom pieces are non-returnable once work begins.',
    faq_q6: 'How do I view a piece in my room (AR)?',
    faq_a6: 'On any product with a 3D model, tap “View in your space” on your phone. The piece appears in your room in the colour and material you selected. For accurate size, the model must be exported at real-world scale (1 unit = 1 metre) or have real-world dimensions set in the admin product form.',
    faq_q7: 'How do I care for my furniture?',
    faq_a7: 'Dust with a soft dry cloth. Keep wood away from direct sunlight and heat sources. For upholstery, blot spills immediately and use a professional cleaner for stains.',
    faq_q8: 'How can I track my order?',
    faq_a8: 'Use the Track Order page with your order number and email. Shipped orders include a tracking number sent by email.',
    staff_title: 'Workshop orders',
    staff_desc: 'Oldest first. Tick each item as you prepare it — progress saves automatically.',
    staff_empty: 'No pending orders. Nice work.',
    refresh: 'Refresh',
    items_ready: 'items ready',
    no_options: 'Standard finish',
    order_complete: 'Order complete',
    order_completed_msg: 'Order completed',
    order_completed_sub: 'Sent to the office for final approval.',
    save_failed: 'Could not save — check your connection',
    reviews_title: 'Reviews',
    write_review: 'Write a review',
    review_placeholder: 'What did you think of this piece?',
    review_submit: 'Submit review',
    review_pending: 'Thanks! Your review will appear after moderation.',
    review_login: 'Sign in to write a review',
    no_reviews: 'No reviews yet — be the first.',
    review_approve: 'Approve',
    review_awaiting: 'Awaiting approval',
    wishlist_title: 'Saved items',
    onboarding_first_name: 'First Name',
    onboarding_last_name: 'Last Name',
    admin_price_egp: 'EGP (Egypt, VAT-incl.)',
    admin_price_usd: 'USD (international)',
    order_confirmed: 'Order confirmed',
    thank_you: 'Thank you for your order',
    confirmation_desc: 'A confirmation has been sent to your email. Keep your order number for reference.',
    order_number: 'Order number',
    paid: 'Paid',
    unpaid: 'Awaiting payment',
    payment_pending: 'Payment pending',
    finish_payment: 'Your order is reserved',
    finish_payment_desc: 'Payment wasn’t completed. Your order is saved — pay on pickup, by transfer, or contact us.',
    view_my_orders: 'View my orders',
    order_not_found: 'Order not found',
    order_not_found_desc: 'We couldn’t find that order number.',
    my_orders: 'My orders',
    no_orders: 'You have no orders yet.',
    items: 'items',
    cookie_title: 'We value your privacy',
    cookie_body: 'We use essential cookies to run the store, and optional analytics cookies to improve it — only with your consent.',
    cookie_learn: 'Learn more',
    cookie_accept: 'Accept all',
    cookie_reject: 'Reject non-essential',
    cookie_customize: 'Customize',
    cookie_settings: 'Cookie settings',
    cookie_necessary: 'Strictly necessary',
    cookie_necessary_desc: 'Authentication, cart, theme & language, security. Always on.',
    cookie_analytics: 'Analytics',
    cookie_analytics_desc: 'Helps us understand usage so we can improve the store. IP-anonymised.',
    cookie_marketing: 'Marketing',
    cookie_marketing_desc: 'Currently unused. Reserved for future advertising — off by default.',
    cookie_save: 'Save preferences',
    privacy_policy: 'Privacy Policy',
    cookie_policy: 'Cookie Policy',
    terms: 'Terms',
    last_updated: 'Last updated',
    hero_subtitle: 'Furniture made to be lived with, crafted, considered, and yours.',
    scroll: 'Scroll',
    collections_kicker: 'Collections',
    craft_kicker: 'Our craft',
    craft_title: 'Made by hand, made to last',
    craft_p1: 'Every piece begins as solid timber and the eye of a craftsman. We joinery-build for decades of use, finish by hand, and obsess over the details you feel but rarely see: the weight of a drawer, the warmth of an edge.',
    craft_p2: 'Choose from our collections or commission a piece to your exact dimensions. Either way, it is built once, and built right.',
    craft_cta: 'Explore the collections',
    craft_image_alt: 'A craftsman finishing a solid-wood frame by hand',
    ar_title: 'See it in your space before you buy',
    ar_subtitle: 'Selected pieces come to life in interactive 3D and augmented reality, so you know it fits, in size and in feel.',
    ar_f1_t: 'View in 3D',
    ar_f1_d: 'Spin every piece and inspect it from any angle.',
    ar_f2_t: 'Place it in your room',
    ar_f2_d: 'Augmented reality at true-to-life scale, right on your floor.',
    ar_f3_t: 'Switch materials live',
    ar_f3_d: 'Try finishes and colours instantly before you decide.',
    ar_cta: 'Browse 3D-ready pieces',
    value_handcrafted: 'Handcrafted',
    value_solid_wood: 'Solid Wood',
    value_made_to_order: 'Made to Order',
    value_delivered: 'Delivered & Installed',
    value_timeless: 'Timeless Design',
    value_egypt: 'Made in Egypt',
    visit_kicker: 'Visit us',
    notfound_title: 'Page not found',
    notfound_desc: 'The page you’re looking for has moved or no longer exists.',
    admin_materials: 'Materials',
    admin_colors: 'Colours',
    admin_dimensions: 'Dimensions',
    admin_comma_separated: 'comma-separated',
    admin_allow_custom_dims: 'Allow customers to request custom dimensions (made to order)',
    explore_collections: 'Explore the collections',
    our_branches: 'Our Branches',
    continue: 'Continue',
    not_now: 'Not now',
    save_address_prompt: 'Save this address to your account for next time?',
    guest_save_prompt: 'Create an account to save your address for future orders?',
    continue_guest: 'Continue as guest',
    address_saved: 'Address saved to your account',
    address_save_failed: 'Could not save address',
    pickup_location: 'Choose a showroom',
    shipping: 'Shipping',
    total: 'Total',
    fulfil_ship: 'Delivery',
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_shop: 'المتجر',
    nav_about: 'عنّا',
    nav_contact: 'تواصل معانا',
    lang_toggle_en: 'English',
    lang_toggle_ar: 'العربية',
    hero_sleek_title: 'مستقبل التصميم',
    hero_cta_explore: 'شوف أكتر',
    products_title: 'مجموعاتنا المميزة',
    products_subtitle: 'قطع مختارة بعناية بتعرّف الأناقة والراحة.',
    visit_us_title: 'زورونا',
    visit_us_p1: 'زوروا معارضنا في القاهرة والمنيا والمنيا الجديدة. لمسوا الأقمشة، شوفوا التشطيبات، واتكلموا مع فريقنا عن القطع المخصّصة — وعلى قهوة لو حابّين.',
    footer_locations_title: 'فروعنا',
    footer_cairo_branch_title: 'فرع القاهرة',
    footer_cairo_branch_address: '٦٦ شارع المؤرخ محمد رفعت بجوار كنتاكي خلف السندباد، النزهة الجديدة',
    footer_minya_branch_title: 'فرع المنيا',
    footer_minya_branch_address: '٦ شارع مصطفي كامل، أرض سلطان',
    footer_new_minya_branch_title: 'فرع المنيا الجديدة',
    footer_new_minya_branch_address: 'مول كورنر بلازا، الدور الثاني، الحي الثالث',
    footer_phone_title: 'تواصل معانا',
    footer_phone_label: 'الهاتف:',
    footer_phone_number: '01010279777',
    footer_hours: 'ساعات العمل: من ١٢ الظهر لـ ١٠ بالليل، من الإثنين للسبت (توقيت مصر)',
    footer_tagline: 'أثاث فاخر مصنوع بإيدينا',
    footer_copyright: '© 2024 رأفت للأثاث. جميع الحقوق محفوظة.',
    product_sofa_name: 'أريكة النيل',
    product_chair_name: 'مقعد فرعون',
    product_table_name: 'طاولة طعام الأقصر',
    product_lamp_name: 'مصباح الجيزة الأرضي',
    product_bed_name: 'سرير كليوباترا',
    product_cabinet_name: 'خزانة الإسكندرية',
    search_placeholder: 'دور على أثاث، ستايلات، والمزيد…',
    cat_living_room: 'غرفة المعيشة',
    cat_sofa_sets: 'أطقم كنَب',
    cat_sectionals: 'كنَب ركني',
    cat_sofas: 'كنَب',
    cat_armchairs: 'كراسي بمساند',
    cat_recliners: 'كراسي استرخاء',
    cat_bedroom: 'غرفة النوم',
    cat_dining_room: 'غرفة السفرة',
    cat_kids_youth: 'غرف الأطفال والشباب',
    cat_office: 'أثاث مكتبي',
    cat_outdoor: 'أثاث خارجي',
    cat_coffee_tables: 'ترابيزات قهوة',
    cat_side_tables: 'ترابيزات جانبية',
    cat_decor_accessories: 'ديكور وإكسسوارات',
    cat_curtains: 'ستاير',
    cat_mattresses: 'مراتب',
    cat_pillows: 'مخدّات',
    // Login & Account
    login_create_account: 'اعمل حساب',
    login_welcome_back: 'نورتنا تاني',
    login_signup_desc: 'سجّل عشان تحفظ تفضيلاتك وتوصلك التحديثات.',
    login_signin_desc: 'سجّل دخول عشان تدخل على حسابك.',
    login_email: 'الإيميل',
    login_password: 'كلمة السر',
    login_creating: 'بنعمل الحساب…',
    login_signing_in: 'بنسجّلك دخول…',
    login_btn_create: 'اعمل حساب',
    login_btn_signin: 'سجّل دخول',
    login_or_continue: 'أو كمّل بـ',
    login_google: 'كمّل بجوجل',
    login_google_only_desc: 'سجّل دخول بجوجل عشان تكمل. ده بيحافظ على أمان حسابك وبيقلل الحسابات الوهمية.',
    login_google_error: 'تسجيل الدخول بجوجل فشل. جرّب تاني.',
    login_terms_note: 'لما تكمّل، إنت موافق على شروط الخدمة وسياسة الخصوصية.',
    use_my_location: 'استخدم موقعي',
    near_hint_placeholder: 'مدينة أو رمز بريدي (مثلاً القاهرة، ١١٧٧١)',
    sort_nearest: 'الأقرب',
    sort_by_my_location: 'رتّب حسب موقعي',
    sort_showrooms: 'رتّب المعارض',
    or_type_city: 'أو اكتب مدينة / رمز بريدي',
    pickup_sort_help: 'رتّب المعارض حسب قربها منك — وبعدين اختار معرض من اللي تحت.',
    geo_unsupported: 'الموقع مش متاح في المتصفح ده.',
    geo_denied: 'ما قدرناش نقرأ موقعك. جرّب مدينة أو رمز بريدي.',
    geo_hint_unknown: 'ما لقيناش المدينة أو الرمز البريدي. جرّب القاهرة أو المنيا أو الإسكندرية أو رمز من ٥ أرقام.',
    billing_for_card: 'الدفع بالبطاقة محتاج عنوان فوترة (عنوان تسجيل البطاقة).',
    pickup_collect_here: 'هتستلم طلبك من المعرض ده.',
    pickup_no_address_needed: 'مفيش عنوان توصيل مع التحويل — الاستلام من المعرض فوق.',
    billing_address: 'عنوان الفوترة',
    pickup_confirm: 'تأكيد الاستلام',
    login_already_have: 'عندك حساب؟ سجّل دخول',
    login_dont_have: 'معندكش حساب؟ اعمل واحد',
    account_title: 'حسابي',
    account_email: 'الإيميل',
    account_signout: 'سجّل خروج',
    // Admin
    admin_dashboard: 'لوحة تحكم الإدارة',
    admin_tab_categories: 'الفئات',
    admin_tab_archive: 'الأرشيف',
    admin_tab_logs: 'سجلات النشاط',
    admin_listings: 'المنتجات',
    admin_add_new: 'إضافة منتج جديد',
    admin_create_new: 'إنشاء منتج جديد',
    admin_name_en: 'اسم المنتج (إنجليزي)',
    admin_name_ar: 'اسم المنتج (عربي)',
    admin_category: 'الفئة',
    admin_price: 'السعر',
    admin_optional: 'اختياري',
    admin_placeholder_price: 'اتركه فارغاً لـ "السعر عند الطلب"',
    admin_desc_en: 'الوصف (إنجليزي)',
    admin_desc_ar: 'الوصف (عربي)',
    admin_auto_translate: 'ترجمة تلقائية للعربية',
    admin_image: 'صورة المنتج',
    admin_upload_image: 'رفع صورة',
    admin_cancel: 'إلغاء',
    admin_btn_create: 'إنشاء المنتج',
    admin_btn_creating: 'جاري الإنشاء...',
    admin_archived: 'المنتجات المؤرشفة',
    admin_restore: 'استعادة',
    admin_delete_perm: 'حذف نهائي',
    admin_delete_perm_warn: 'الحذف النهائي بيمسح المنتج وصوره خالص ومفيش رجوع فيه.',
    admin_recent_activity: 'النشاط الأخير',
    admin_no_logs: 'لا توجد سجلات متاحة.',
    admin_no_listings: 'لم يتم العثور على منتجات في هذه الفئة.',
    admin_no_archived: 'لم يتم العثور على منتجات مؤرشفة.',
    admin_delete: 'حذف',
    admin_archive: 'أرشفة',
    admin_edit: 'تعديل',
    admin_save: 'حفظ',
    admin_edit_listing: 'تعديل المنتج',
    admin_update_listing: 'تحديث المنتج',
    admin_panel: 'لوحة تحكم الإدارة',
    admin_back_to_site: 'العودة للموقع',
    admin_select_category: 'حدد فئة لعرض أو إضافة منتجات.',
    admin_items: 'عناصر',
    admin_pending_deletion: 'في انتظار الحذف',
    admin_days_left: 'أيام متبقية قبل الحذف',
    admin_recover: 'استعادة',
    admin_time: 'الوقت',
    admin_admin: 'المسؤول',
    admin_action: 'الإجراء',
    admin_details: 'التفاصيل',
    admin_photo_min: 'الصورة (واحدة على الأقل)',
    admin_click_to_change: 'انقر للتغيير',
    admin_click_to_upload: 'انقر لرفع صورة',
    admin_photo_format: 'PNG, JPG حتى 5 ميجابايت',
    admin_change_photo: 'تغيير الصورة',
    admin_alert_image_required: 'صورة المنتج مطلوبة',
    account_admin: 'مسؤول',
    admin_post_listing: 'نشر المنتج',
    admin_remove_listing: 'هل تريد إزالة هذا المنتج؟',
    admin_archived_auto_remove: 'ستتم إزالة المنتجات المؤرشفة تلقائيًا بعد 14 يومًا.',
    admin_access_denied: 'تم رفض الوصول',
    coming_soon_title: 'قريبًا',
    coming_soon_body: 'بنحط اللمسات الأخيرة على حاجة مميزة. سيّب بياناتك وهنقولك أول ما نفتح.',
    coming_soon_scheduled: 'موعد الافتتاح المتوقع',
    coming_soon_notify: 'بلّغوني',
    coming_soon_name: 'اسمك',
    coming_soon_email: 'الإيميل',
    coming_soon_phone: 'الموبايل (اختياري)',
    coming_soon_success: 'اتسجّلت. هنبعتلك إيميل لما نفتح.',
    coming_soon_privacy: 'هنستخدم بياناتك بس علشان نبلّغك بالافتتاح. راجع سياسة الخصوصية.',
    coming_soon_sign_in: 'من الفريق؟ سجّل دخول',
    admin_not_authorized: 'بريدك الإلكتروني ({email}) غير مصرح له بعرض هذه الصفحة. يرجى الاتصال بالمسؤول.',
    admin_placeholder_name_en: 'مثال: أريكة حديثة',
    admin_placeholder_name_ar: 'أريكة حديثة',
    admin_placeholder_desc_en: 'تفاصيل المنتج...',
    admin_placeholder_desc_ar: 'تفاصيل المنتج...',
    admin_alert_name_required: 'يرجى تقديم اسم المنتج بلغة واحدة على الأقل.',
    admin_alert_desc_required: 'يرجى تقديم وصف للمنتج بلغة واحدة على الأقل.',
    admin_alert_translate_failed: 'فشلت الترجمة التلقائية. يرجى ملء جميع الحقول يدوياً أو المحاولة مرة أخرى.',
    admin_alert_delete_failed: 'فشل حذف المنتج.',
    admin_alert_create_failed: 'فشل إنشاء المنتج: ',
    nav_go_back: 'ارجع',
    shop_not_found: 'القسم ده مش موجود.',
    shop_return_home: 'ارجع للرئيسية',
    shop_artisans_work: 'الحرفيين شغالين',
    shop_curating_desc: 'لسه بنجهّز المجموعة دي. ارجع قريب هتلاقي قطع جديدة.',
    search_results_for: 'نتائج البحث عن',
    search_no_results: 'مفيش نتائج لـ',
    product_not_found: 'المنتج مش موجود',
    product_return_home: 'ارجع للرئيسية',
    product_inquire_now: 'اسأل دلوقتي',
    add_to_cart: 'ضيف للسلة',
    product_fallback_desc: 'هذا عرض تفصيلي لـ {name}. في نظام إدارة المحتوى المكتمل، سيتم جلب هذا الوصف من قاعدة البيانات، مما يسمح للمسؤولين بتحديث النص والمواصفات والصور الإضافية بشكل آمن.',
    aria_close_search: 'إغلاق البحث',
    aria_switch_light: 'التبديل للوضع الفاتح',
    aria_switch_dark: 'التبديل للوضع الداكن',
    aria_account: 'الحساب',
    aria_open_menu: 'فتح القائمة',
    aria_close_menu: 'إغلاق القائمة',
    mobile_nav: 'التنقل الرئيسي',
    aria_logo: 'شعار رأفت للأثاث',
    cart: 'السلة',
    cart_empty: 'السلة لسه فاضية.',
    continue_shopping: 'كمّل تسوّق',
    save_for_later: 'احفظ لبعدين',
    saved_for_later: 'اتحفظ لبعدين',
    move_to_cart: 'انقل للسلة',
    remove: 'شيل',
    subtotal: 'المجموع الفرعي',
    shipping_taxes_calculated: 'الشحن والضرايب بتتساب عند الدفع.',
    checkout: 'إتمام الشراء',
    sign_in_to_save: 'سجّل دخول عشان تحفظ القطع',
    create_account_wishlist: 'اعمل حساب أو سجّل دخول عشان تحفظ القطع في قائمة الأمنيات.',
    sign_in: 'سجّل دخول',
    create_account: 'اعمل حساب',
    cancel: 'إلغاء',
    price_on_request: 'السعر عند الطلب',
    clear_filters: 'امسح الفلاتر',
    skip_to_content: 'تخطّى للمحتوى',
    color: 'اللون',
    material: 'الخامة',
    dimensions: 'الأبعاد',
    custom_dimensions: 'مقاسات مخصوصة (اختياري)',
    custom_dimensions_hint: 'قولنا المقاس اللي عايزه — هنصنعه حسب الطلب.',
    custom_dimensions_ph: 'مثال: عرض ٢٢٠ سم × عمق ٩٥ سم',
    add_to_cart_label: 'ضيف للسلة',
    added: 'اتضاف',
    added_to_cart: 'اتضاف للسلة',
    in_cart_view: 'في السلة — شوفها',
    in_cart: 'في السلة',
    ar_back: 'رجوع',
    instapay_send: 'ابعت',
    instapay_to: 'من أي تطبيق بنكي مصري إلى',
    instapay_ref_hint: 'بعد ما تبعت، الصق رقم العملية من التطبيق علشان نأكد الدفع.',
    ar_exit_hint: 'ارجع للخلف علشان ترجع للمنتج',
    decrease_quantity: 'قلّل الكمية',
    increase_quantity: 'زوّد الكمية',
    save: 'حفظ',
    saved: 'محفوظ',
    view_3d: '٣D والواقع المعزّز',
    view_photos: 'الصور',
    viewer_view_in_ar: 'شوفه في مكانك',
    viewer_reset: 'رجّع العرض',
    viewer_3d_badge: '٣D',
    viewer_ar_qr_title: 'شوفه بالواقع المعزّز على موبايلك',
    viewer_ar_qr_desc: 'امسح الكود بموبايلك عشان تفتح الموديل في الواقع المعزّز.',
    viewer_ar_qr_hint: 'امسح عشان تفتح الواقع المعزّز',
    prev_image: 'الصورة اللي قبلها',
    next_image: 'الصورة اللي بعدها',
    toggle_wishlist: 'قائمة الأمنيات',
    checkout_title: 'إتمام الشراء',
    order_summary: 'ملخّص الطلب',
    place_order: 'أكّد الطلب',
    pay_now: 'ادفع دلوقتي',
    secure_checkout: 'دفع آمن',
    checkout_terms_note: 'لما تأكّد طلبك، فأنت موافق على',
    checkout_terms_and: 'و',
    your_details: 'بياناتك',
    how_to_receive: 'عايز تستلم إزاي؟',
    delivery_address: 'عنوان التوصيل',
    payment: 'الدفع',
    full_name: 'الاسم بالكامل',
    phone: 'الموبايل',
    phone_optional_hint: 'اختياري — بيساعدنا نتواصل معاك بخصوص الطلب',
    no_payment_methods: 'مفيش طرق دفع متاحة دلوقتي. كلّم المتجر أو جرّب بعدين.',
    address: 'العنوان',
    city: 'المدينة',
    governorate: 'المحافظة',
    country: 'الدولة',
    postal_code: 'الرمز البريدي',
    order_note: 'ملاحظة للمتجر (اختياري)',
    free: 'مجاني',
    shipping_tbd: 'بيتأكّد بعد الطلب',
    fulfil_pickup: 'استلام من المعرض',
    fulfil_shipping: 'توصيل',
    fulfil_custom: 'طلب مخصوص',
    fulfil_pickup_desc: 'استلم من أحد معارض رأفت',
    custom_order_title: 'محتاج حاجة مخصوصة؟',
    custom_order_checkout_note: 'القطع المخصوصة بيتسعّرها فريقنا — كلّمنا بالمواصفات قبل ما تطلب.',
    contact_us: 'تواصل معانا',
    fulfil_ship_desc: 'هيتوصّل لعنوانك',
    fulfil_custom_desc: 'بتتصنع حسب مواصفاتك',
    pay_card: 'بطاقة / Apple Pay / Google Pay',
    pay_pickup: 'كاش عند الاستلام',
    pay_pickup_desc: 'ادفع في المعرض (مصر بس)',
    pay_cod: 'كاش عند التوصيل',
    pay_bank: 'تحويل بنكي',
    pay_instapay: 'إنستاباي',
    pay_instapay_desc: 'حوّل من أي تطبيق بنكي مصري',
    card_soon: 'الدفع بالبطاقة هيبقى متاح قريب. اختار إنستاباي أو التحويل البنكي دلوقتي.',
    shipping_prepaid_note: 'طلبات التوصيل بتتدفع كاملة وإنت بتعمل الطلب. تكلفة الشحن المتجر بيأكّدها قبل الإرسال.',
    custom_deposit_note: 'الطلبات المخصوصة محتاجة عربون ومش هتتقبل الإرجاع بعد ما التصنيع يبدأ. فريقنا هيتواصل معاك يأكّد التفاصيل.',
    transfer_note: 'هتوصلك تفاصيل التحويل في الصفحة الجاية. طلبك بيتأكّد بعد ما نتأكّد من الدفع.',
    vat_included: 'ضريبة القيمة المضافة ١٤٪ (مشمولة)',
    tax_export: 'الضريبة',
    tax_export_value: '٠٪ (تصدير)',
    duties_note: 'الجمارك والضرايب، لو فيه، بتتساب في بلدك عند التسليم.',
    tax: 'الضريبة',
    receipt: 'الإيصال',
    verifying_payment: 'بنراجع الدفع',
    view_order: 'شوف طلبك',
    confirm_email_prompt: 'اكتب الإيميل اللي استخدمته في الطلب عشان تشوف الإيصال.',
    pay_with_instapay: 'ادفع بإنستاباي',
    pay_by_transfer: 'ادفع بتحويل بنكي',
    instapay_step1: 'ابعت المبلغ اللي تحت من أي تطبيق بنكي مصري لعنوان إنستاباي بتاعنا:',
    bank_step1: 'حوّل المبلغ اللي تحت على حسابنا البنكي:',
    instapay_note_label: 'في ملاحظة / عنوان التحويل اكتب بالظبط:',
    instapay_note_hint: 'رقم الطلب + اسمك. بكده بنطابق الدفع.',
    transfer_step2: 'انسخ رقم العملية من التطبيق.',
    transfer_step3: 'الصقه تحت عشان نتأكّد من الدفع.',
    transfer_details_soon: 'فريقنا هيبعتلك تفاصيل التحويل على الإيميل قريب.',
    payment_reference: 'رقم العملية',
    submit_reference: 'إرسال',
    reference_submitted: 'اتبعت الرقم — هنراجع الدفع قريب.',
    reference_received: 'استلمنا رقم التحويل وبنتأكّد منه دلوقتي. هتوصلك رسالة تأكيد بعد الموافقة.',
    copied: 'اتنسخ',
    tracking_number: 'رقم التتبّع',
    track_order: 'تتبّع الطلب',
    track_title: 'تتبّع طلبك',
    track_desc: 'اكتب رقم الطلب والإيميل اللي استخدمته وإنت بتشتري.',
    track_cta: 'تتبّع',
    step_awaiting_payment: 'مستني الدفع',
    step_confirmed: 'الطلب اتأكّد',
    step_preparing: 'بيتتجهّز',
    step_ready: 'جاهز',
    step_shipped: 'اتشحن / مستني الاستلام',
    step_completed: 'اكتمل',
    cancelled: 'اتلغى',
    order_cancelled_desc: 'الطلب ده اتلغى. كلّمنا لو ده مش متوقع.',
    contact_title: 'تواصل معانا',
    contact_desc: 'عندك سؤال عن قطعة أو طلب مخصوص أو التوصيل؟ بنرد في خلال يوم شغل واحد.',
    contact_whatsapp: 'واتساب',
    contact_phone: 'الموبايل',
    contact_form_title: 'ابعتلنا رسالة',
    contact_message: 'الرسالة',
    contact_send: 'ابعت الرسالة',
    contact_sent: 'الرسالة اتبعتت',
    contact_sent_desc: 'شكرًا — هنرد عليك قريب.',
    faq_short: 'أسئلة شائعة',
    faq_title: 'أسئلة شائعة',
    faq_desc: 'كل اللي محتاج تعرفه عن الطلب والتوصيل والإرجاع والعناية.',
    faq_more: 'لسه عندك سؤال؟',
    faq_q1: 'التوصيل بياخد قد إيه؟',
    faq_a1: 'مدة التوصيل بتتساب لكل طلب لوحده — جاهز أو مخصوص، جوه مصر أو برّه. فريقنا بيأكّد المدة قبل الإرسال.',
    faq_q2: 'بتوصلوا برّه مصر؟',
    faq_a2: 'أيوه — بنشحن لكل العالم. طلبات التوصيل بتتدفع كاملة وإنت بتعمل الطلب، وتكلفة الشحن بتتأكّد قبل الإرسال. الجمارك، لو فيه، بتتساب في بلدك عند التسليم.',
    faq_q3: 'طرق الدفع إيه؟',
    faq_a3: 'بطاقة (شاملة Apple Pay وGoogle Pay) وإنستاباي وتحويل بنكي وكاش عند الاستلام من معارضنا في مصر. طلبات التوصيل لازم تتدفع قبل الشحن.',
    faq_q4: 'أقدر أرجّع قطعة؟',
    faq_a4: 'القطع الجاهزة تقدر ترجعها خلال ١٤ يوم من التسليم وهي زي ما هي. القطع المخصوصة والمصنوعة حسب الطلب مش هتتقبل الإرجاع بعد ما التصنيع يبدأ. شوف السياسة كاملة في الشروط.',
    faq_q5: 'الطلبات المخصوصة بتتم إزاي؟',
    faq_a5: 'كلّمنا من صفحة التواصل أو واتساب بالمواصفات. هنأكّد التصميم والأبعاد والخامات والسعر، وناخد عربون، وبعدين نبدأ التصنيع. القطع المخصوصة مش هتتقبل الإرجاع.',
    faq_q6: 'أزاي أشوف القطعة في أوضتي (واقع معزّز)؟',
    faq_a6: 'على أي منتج فيه موديل ٣D، اضغط «شوفه في مكانك» من الموبايل. القطعة هتظهر في الأوضة باللون والخامة اللي اختارتها. عشان المقاس يبقى مضبوط، الموديل لازم يتصدّر بمقاس حقيقي (وحدة = متر) أو تتسجّل الأبعاد الحقيقية في لوحة المنتج.',
    faq_q7: 'أزاي أعتني بالأثاث؟',
    faq_a7: 'امسح بفوطة ناعمة ناشفة. خلّي الخشب بعيد عن الشمس المباشرة ومصادر الحرارة. للتقليم، امسح السوائل فورًا واستخدم منظّف محترف للبقع.',
    faq_q8: 'أزاي أتتبّع طلبي؟',
    faq_a8: 'استخدم صفحة تتبّع الطلب برقم الطلب والإيميل. الطلبات اللي اتشحنت بيبقى معاها رقم تتبّع على الإيميل.',
    staff_title: 'طلبات الورشة',
    staff_desc: 'الأقدم الأول. علّم على كل قطعة وإنت بتجهّزها — التقدم بيتحفظ لوحده.',
    staff_empty: 'مافيش طلبات معلّقة. شغل جميل.',
    refresh: 'تحديث',
    items_ready: 'عناصر جاهزة',
    no_options: 'تشطيب قياسي',
    order_complete: 'اكتمل الطلب',
    order_completed_msg: 'تم إكمال الطلب',
    order_completed_sub: 'أُرسل إلى الإدارة للاعتماد النهائي.',
    save_failed: 'تعذّر الحفظ — تحقق من اتصالك',
    reviews_title: 'التقييمات',
    write_review: 'اكتب تقييم',
    review_placeholder: 'إيه رأيك في القطعة دي؟',
    review_submit: 'ابعت التقييم',
    review_pending: 'شكرًا! تقييمك هيظهر بعد المراجعة.',
    review_login: 'سجّل دخول عشان تكتب تقييم',
    no_reviews: 'لسه مفيش تقييمات — كون أول واحد.',
    review_approve: 'اعتماد',
    review_awaiting: 'بانتظار الاعتماد',
    wishlist_title: 'المحفوظات',
    onboarding_first_name: 'الاسم الأول',
    onboarding_last_name: 'اسم العيلة',
    admin_price_egp: 'ج.م (مصر، شامل الضريبة)',
    admin_price_usd: 'دولار (دولي)',
    order_confirmed: 'الطلب اتأكّد',
    thank_you: 'شكرًا على طلبك',
    confirmation_desc: 'اتبعت تأكيد على إيميلك. احتفظ برقم الطلب للرجوع.',
    order_number: 'رقم الطلب',
    paid: 'مدفوع',
    unpaid: 'بانتظار الدفع',
    payment_pending: 'الدفع معلّق',
    finish_payment: 'طلبك محجوز',
    finish_payment_desc: 'الدفع ما اكتملش. طلبك محفوظ — تقدر تدفع عند الاستلام أو بالتحويل أو تتواصل معانا.',
    view_my_orders: 'عرض طلباتي',
    order_not_found: 'الطلب غير موجود',
    order_not_found_desc: 'لم نتمكّن من إيجاد رقم الطلب هذا.',
    my_orders: 'طلباتي',
    no_orders: 'ليس لديك طلبات بعد.',
    items: 'عناصر',
    cookie_title: 'نحترم خصوصيتك',
    cookie_body: 'بنستخدم ملفات ضرورية عشان المتجر يشتغل، وملفات تحليلات اختيارية عشان نحسّنه — بموافقتك بس.',
    cookie_learn: 'اعرف أكتر',
    cookie_accept: 'اقبل الكل',
    cookie_reject: 'ارفض غير الضروري',
    cookie_customize: 'خصّص',
    cookie_settings: 'إعدادات الكوكيز',
    cookie_necessary: 'ضرورية تمامًا',
    cookie_necessary_desc: 'تسجيل الدخول، السلة، الثيم واللغة، والأمان. دايمًا شغّالة.',
    cookie_analytics: 'التحليلات',
    cookie_analytics_desc: 'بتساعدنا نفهم الاستخدام عشان نحسّن المتجر. الـ IP متخفّي.',
    cookie_marketing: 'التسويق',
    cookie_marketing_desc: 'مش مستخدمة دلوقتي. محجوزة لإعلانات مستقبلية — مقفولة افتراضيًا.',
    cookie_save: 'احفظ التفضيلات',
    privacy_policy: 'سياسة الخصوصية',
    cookie_policy: 'سياسة الكوكيز',
    terms: 'الشروط',
    last_updated: 'آخر تحديث',
    hero_subtitle: 'أثاث اتعمل عشان تعيش معاه — متقن، مدروس، وبتاعك.',
    scroll: 'انزل',
    collections_kicker: 'المجموعات',
    craft_kicker: 'حِرفتنا',
    craft_title: 'اتعمل باليد، عشان يفضل سنين',
    craft_p1: 'كل قطعة بتبدأ من خشب صلب وعين حرفي. بنركّبها عشان تفضل عقود، وبنخلّصها بإيدينا، وبنهتم بالتفاصيل اللي بتحسّها ومش دايمًا بتشوفها: ثِقل الدرج، ودفء الحافة.',
    craft_p2: 'اختار من مجموعاتنا أو اطلب قطعة بمقاساتك بالظبط. في الحالتين، بتتعمل مرة واحدة، وبتتعمل صح.',
    craft_cta: 'شوف المجموعات',
    craft_image_alt: 'حرفي بيخلّص إطار من الخشب الصلب بإيده',
    ar_title: 'شوفها في مكانك قبل ما تشتري',
    ar_subtitle: 'قطع مختارة بتعيش قدامك بـ 3D وواقع معزّز، عشان تتأكد إنها مناسبة لمساحتك حجمًا وإحساسًا.',
    ar_f1_t: 'عرض ثلاثي الأبعاد',
    ar_f1_d: 'أدِر كل قطعة وافحصها من أي زاوية.',
    ar_f2_t: 'ضعها في غرفتك',
    ar_f2_d: 'واقع معزّز بمقاس حقيقي، على أرضك مباشرة.',
    ar_f3_t: 'بدّل الخامات مباشرة',
    ar_f3_d: 'جرّب التشطيبات والألوان فوراً قبل أن تقرّر.',
    ar_cta: 'تصفّح القطع ثلاثية الأبعاد',
    value_handcrafted: 'صناعة يدوية',
    value_solid_wood: 'خشب صلب',
    value_made_to_order: 'يُصنع حسب الطلب',
    value_delivered: 'توصيل وتركيب',
    value_timeless: 'تصميم خالد',
    value_egypt: 'صُنع في مصر',
    visit_kicker: 'زورونا',
    notfound_title: 'الصفحة غير موجودة',
    notfound_desc: 'الصفحة التي تبحث عنها انتقلت أو لم تعد موجودة.',
    admin_materials: 'الخامات',
    admin_colors: 'الألوان',
    admin_dimensions: 'الأبعاد',
    admin_comma_separated: 'مفصولة بفواصل',
    admin_allow_custom_dims: 'السماح للعملاء بطلب أبعاد مخصّصة (تُصنع حسب الطلب)',
    explore_collections: 'شوف المجموعات',
    our_branches: 'فروعنا',
    continue: 'كمّل',
    not_now: 'مش دلوقتي',
    save_address_prompt: 'تحفظ العنوان ده في حسابك للمرات الجاية؟',
    guest_save_prompt: 'تعمل حساب عشان تحفظ عنوانك للطلبات الجاية؟',
    continue_guest: 'كمّل كزائر',
    address_saved: 'العنوان اتحفظ في حسابك',
    address_save_failed: 'ما قدرناش نحفظ العنوان',
    pickup_location: 'اختار معرض',
    shipping: 'الشحن',
    total: 'الإجمالي',
    fulfil_ship: 'توصيل',
  }
};

export const CATEGORIES: Category[] = [
  { 
    id: 'living_room', 
    labelKey: 'cat_living_room', 
    imageUrl: 'https://picsum.photos/seed/livingroom/800/600',
    subCategories: [
      { id: 'sofa_sets', labelKey: 'cat_sofa_sets', imageUrl: 'https://picsum.photos/seed/sofaset/800/600' },
      { id: 'sectionals', labelKey: 'cat_sectionals', imageUrl: 'https://picsum.photos/seed/sectional/800/600' },
      { id: 'sofas', labelKey: 'cat_sofas', imageUrl: 'https://picsum.photos/seed/sofa/800/600' },
      { id: 'armchairs', labelKey: 'cat_armchairs', imageUrl: 'https://picsum.photos/seed/armchair/800/600' },
      { id: 'recliners', labelKey: 'cat_recliners', imageUrl: 'https://picsum.photos/seed/recliner/800/600' },
    ]
  },
  { id: 'bedroom', labelKey: 'cat_bedroom', imageUrl: 'https://picsum.photos/seed/bedroom/800/600' },
  { id: 'dining_room', labelKey: 'cat_dining_room', imageUrl: 'https://picsum.photos/seed/dining/800/600' },
  { id: 'kids_youth', labelKey: 'cat_kids_youth', imageUrl: 'https://picsum.photos/seed/kidsroom/800/600' },
  { id: 'office', labelKey: 'cat_office', imageUrl: 'https://picsum.photos/seed/office/800/600' },
  { id: 'outdoor', labelKey: 'cat_outdoor', imageUrl: 'https://picsum.photos/seed/outdoor/800/600' },
  { id: 'coffee_tables', labelKey: 'cat_coffee_tables', imageUrl: 'https://picsum.photos/seed/coffeetable/800/600' },
  { id: 'side_tables', labelKey: 'cat_side_tables', imageUrl: 'https://picsum.photos/seed/sidetable/800/600' },
  { id: 'decor_accessories', labelKey: 'cat_decor_accessories', imageUrl: 'https://picsum.photos/seed/decor/800/600' },
  { id: 'curtains', labelKey: 'cat_curtains', imageUrl: 'https://picsum.photos/seed/curtains/800/600' },
  { id: 'mattresses', labelKey: 'cat_mattresses', imageUrl: 'https://picsum.photos/seed/mattress/800/600' },
  { id: 'pillows', labelKey: 'cat_pillows', imageUrl: 'https://picsum.photos/seed/pillows/800/600' }
];